---
apiVersion: v1
kind: application
metadata:
  name: devtest.latencyresponder
  commType: event
spec:
  services:
    - serviceName: latencyresponder
      components:
        - componentName: latencyresponder
          imageType: docker
          imageName: latencyresponder
          interfaces:
            - interfaceName: ping
              interfaceType: event
              upstreamPath: latencyresponder.event_handler
              visiblity: external
              accessList:
                - app@client
          resourceProfiles:
            - resourceProfileName: default
              memory: 1024
              cpu: 1
          defaultResourceProfile: default

